{{- $traefikEnabled := eq (include "ods.traefikEnabled" .) "true" -}}
{{- if and .Values.ingress.enabled $traefikEnabled .Values.ingress.tls.enabled .Values.ingress.tls.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ include "ods.fullname" . }}
    kind: Issuer
  dnsNames:
    {{- range .Values.ingress.traefik.hosts | default (list .Values.ingress.host) }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
