{{- $controller := include "ods.ingressController" . -}}
{{- if and .Values.ingress.enabled (eq $controller "traefik") .Values.ingress.tls.enabled .Values.ingress.tls.acme.enabled }}
{{- $hosts := concat (list .Values.ingress.host) (.Values.ingress.additionalHosts | default (list)) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ include "ods.fullname" . }}
    kind: Issuer
  dnsNames:
    {{- range $hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
