{{- $ingress := get .Values "ingress" | default dict -}}
{{- $traefik := get $ingress "traefik" | default dict -}}
{{- $traefikEnabled := get $traefik "enabled" | default false -}}

{{- if .Values.ingress.enabled -}}
{{- if not $traefikEnabled }}

{{- /* Default .Values.ingress.annotations to dict if nil AND reassign it */}}
{{- if not .Values.ingress.annotations -}}
  {{- $_ := set .Values.ingress "annotations" dict -}}
{{- end -}}

{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className -}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ods.labels" . | indent 4 }}
  annotations:
  {{- $mergedAnnotations := dict }}
  {{- if and $.Values.ingress.tls.enabled $.Values.ingress.tls.acme.enabled }}
    {{- $_ := set $mergedAnnotations "cert-manager.io/issuer" (include "ods.fullname" .) }}
  {{- end }}
  {{- if .Values.ingress.annotations }}
    {{- $mergedAnnotations = merge $mergedAnnotations (default dict .Values.ingress.annotations) }}
  {{- end }}
  {{- if get .Values.ingress "nginx" | default dict }}
    {{- $nginx := get .Values.ingress "nginx" | default dict }}
    {{- if $nginx.annotations }}
      {{- $mergedAnnotations = merge $mergedAnnotations (default dict $nginx.annotations) }}
    {{- end }}
  {{- end }}
  {{- if $mergedAnnotations }}
    {{- toYaml $mergedAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "ods.fullname" $ }}
                port:
                  name: "http"
              {{- else }}
              serviceName: {{ include "ods.fullname" $ }}
              servicePort: {{ default "80" .Values.service.ports.http }}
              {{- end }}
{{- end }}
{{- if $traefikEnabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "ods.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ods.labels" . | indent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.sshEntryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "ods.fullname" . }}{{- if .Values.service.separateSSH.enabled }}-ssh{{- end }}
        {{- if .Values.service.separateSSH.enabled }}
          port: {{ default .Values.service.ports.ssh .Values.service.separateSSH.port | default "22" }}
        {{- else }}
          port: {{ default "22" .Values.service.ports.ssh }}
        {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ods.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ods.labels" . | indent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entryPoint }}
  routes:
  {{- if .Values.ingress.traefik.hosts }}
    {{- $hosts := list }}
    {{- range .Values.ingress.traefik.hosts }}
      {{- $hosts = append $hosts (regexReplaceAll "\\." . "\\.") }}
    {{- end }}
  - match: HostRegexp(`^({{ join "|" $hosts }})$`)
  {{- else }}
  - match: Host(`{{ .Values.ingress.host }}`)
  {{- end }}
    kind: Rule
    middlewares:
      - name: {{ include "ods.fullname" . }}-{{ .Values.ingress.traefik.middleware.name }}
        namespace: {{ .Release.Namespace }}
    services:
    - name: {{ include "ods.fullname" . }}
      port: {{ default "80" .Values.service.ports.http }}
      sticky:
        cookie:
          httpOnly: true
{{- if .Values.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ods.fullname" . }}-{{ .Values.ingress.traefik.middleware.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ods.labels" . | indent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ int .Values.ingress.traefik.middleware.maxRequestBodyBytes }}
    memRequestBodyBytes: {{ int .Values.ingress.traefik.middleware.memRequestBodyBytes }}
{{- end }}
{{- end }}
