#!/bin/sh
set -e
unset http_proxy
unset https_proxy
%s
response=$(${ONEDEV_CURL} -k -s -S -w '\n%%{http_code}' ${ONEDEV_URL}/git-workspace-postcommit-callback/${ONEDEV_HOOK_TOKEN} 2>&1) || {
  echo "$response"
  exit 1
}
http_code=$(echo "$response" | tail -n1)
body=$(echo "$response" | sed '$d')
if [ "$http_code" -ge 400 ] 2>/dev/null; then
  if [ -n "$body" ]; then
    echo "curl($http_code): $body"
  else
    echo "curl($http_code): HTTP error"
  fi
  exit 1
fi
