#!/bin/bash
IFS=$'\r\n'; 
lines=($(curl -k -s -S -f -X POST -d @- ${GITOP_URL}/git-postreceive-callback/${GITOP_REPOSITORY_ID}/${GITOP_USER_ID} 2>&1))

returnCode=0;

for i in ${lines[@]}
do
  if [ "$i" = "ERROR" ]; then 
    returnCode=1
  else
    if [[ $i == curl:* ]]; then
      returnCode=1
    fi;
    echo "$i"
  fi;
done

exit $returnCode