#!/bin/sh
IFS=$'\r\n'; 
lines=($(
curl -k -s -S -f -X POST -d @- ${GITPLEX_URL}/git-update-callback/${GITPLEX_REPOSITORY_ID}/${GITPLEX_USER_ID} 2>&1 <<EOF
$1 $2 $3
EOF
))

returnCode=0;

for i in ${lines[@]}
do
  if [ "$i" = "ERROR" ]; then 
    returnCode=1
  else
    if [[ $i == curl:* ]]; then
      returnCode=1
    fi;
    echo "$i"
  fi;
done

exit $returnCode