package io.onedev.server.plugin.pack.container;

public enum ErrorCode {
	BLOB_UNKNOWN, BLOB_UPLOAD_INVALID, BLOB_UPLOAD_UNKNOWN, DIGEST_INVALID, MANIFEST_BLOB_UNKNOWN,
	MANIFEST_INVALID, MANIFEST_UNKNOWN, NAME_INVALID, NAME_UNKNOWN, SIZE_INVALID, UNAUTHORIZED,
	DENIED, UNSUPPORTED, TOOMANYREQUESTS
}
