name: Basic ci pipeline

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test onedev - Server Core
      run: mvn --batch-mode --update-snapshots -pl server-core, server-product -am verify

    # - name: Test onedev - Server Product
    #   run: mvn --batch-mode --update-snapshots -pl server-product -am verify

