name: Basic ci pipeline

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test onedev - Server Core
      run: cp server-core & mvn -N --batch-mode --update-snapshots verify

    - name: Test onedev - Server Product
      run: cp server-product & mvn -N --batch-mode --update-snapshots verify

